---
title: "Attachment B"
output:
  pdf_document: default
  html_document: default
---
## Attachment B

Statistical analysis about tumours counting data comparasion of 12 months before COVID and 12 months after, in Modena province.

```{r setup, include=FALSE}
rm(list = ls()) # delete previous data in memory
knitr::opts_chunk$set(echo = TRUE)
library(tidyquery)
library(ggplot2)
library(MASS)
library(dplyr)

# Function for creating dummy variables
make.dummy=function(n, freq=12, start=1){
dv=matrix(0,nrow=(n+start-1), ncol=freq)
for (i in 1:freq)
dv[,i][seq(i,n+start-1,freq)] = 1
return(dv[start:(n+start-1),])
}
```

### Import of the datasets
```{r}
df_pre <- read.csv("df_pre_17.csv")
df_post <- read.csv("df_post_17.csv")
```

#### horizontal monthly dataframe
```{r}

df_pre = query(
" SELECT *
  FROM df_pre
  ORDER BY Year, Month;"
)
df_pre_m = query(
" SELECT Month,Year, COUNT(*)
  FROM df_pre
  GROUP BY Year,Month;"
)

df_post = query(
" SELECT *
  FROM df_post
  ORDER BY Year, Month;"
)
df_post_m = query(
" SELECT Month,Year, COUNT(*)
  FROM df_post
  GROUP BY Year,Month;"
)

df_h = as.data.frame(cbind(df_pre_m[,3],df_post_m[,3]))
colnames(df_h) = c("before","after") # columns names
```

#### from horizontal to vertical monthly dataframe
```{r}
#### Vertical Dataframe
df_v = as.data.frame(matrix(data=c(df_h[,1],df_h[,2],rep(0,17),rep(1,17)),
                                   nrow = 34,ncol = 2, byrow =F))
colnames(df_v) =c("count","covid")
df_v$covid = as.factor(df_v$covid)
```


```{r}
(1-(sum(df_v$count[df_v$covid==1])/sum(df_v$count[df_v$covid==0])))*100
```


#### horizontal monthly dataframe
```{r}
df_pre <- read.csv("df_pre_17.csv")
df_post <- read.csv("df_post_17.csv")

# df_pre2= df_pre %>% group_by(SESSO)


df_pre_sex<-df_pre %>%
  count(SESSO)

df_post_sex<-df_post %>%
  count(SESSO)

df_pre_age<-df_pre %>%
  count(AgeCod)

df_post_age<-df_post %>%
  count(AgeCod)

df_pre_hist<-df_pre %>%
  count(ISTOLOGIA)

df_post_hist<-df_post %>%
  count(ISTOLOGIA)
```

Dati tabella paper - cali percentuali
```{r}
# totale
(dim(df_pre)[1] - dim(df_post)[1])/dim(df_pre)[1]
# sesso
(df_pre_sex[1,2] - df_post_sex[1,2])/df_pre_sex[1,2] # femmine
(df_pre_sex[2,2] - df_post_sex[2,2])/df_pre_sex[2,2] # maschi
# agecod
(df_pre_age[1,2] - df_post_age[1,2])/df_pre_age[1,2] # 1
(df_pre_age[2,2] - df_post_age[2,2])/df_pre_age[2,2] # 2
(df_pre_age[3,2] - df_post_age[3,2])/df_pre_age[3,2] # 3
(df_pre_age[4,2] - df_post_age[4,2])/df_pre_age[4,2] # 4
(df_pre_age[5,2] - df_post_age[5,2])/df_pre_age[5,2] # 5
# istologia
(df_pre_hist[1,2] - df_post_hist[1,2])/df_pre_hist[1,2] # 1
(df_pre_hist[2,2] - df_post_hist[2,2])/df_pre_hist[2,2] # 2
(df_pre_hist[3,2] - df_post_hist[3,2])/df_pre_hist[3,2] # 3
(df_pre_hist[4,2] - df_post_hist[4,2])/df_pre_hist[4,2] # 4
```

```{r}
1-(df_pre_sex[1,2]/(df_pre_sex[1,2]+df_post_sex[1,2]))
1-(df_pre_sex[2,2]/(df_pre_sex[2,2]+df_post_sex[2,2]))
1-(df_pre_age[1,2]/(df_pre_age[1,2]+df_post_age[1,2]))
1-(df_pre_age[2,2]/(df_pre_age[2,2]+df_post_age[2,2]))
1-(df_pre_age[3,2]/(df_pre_age[3,2]+df_post_age[3,2]))
1-(df_pre_age[4,2]/(df_pre_age[4,2]+df_post_age[4,2]))
1-(df_pre_age[5,2]/(df_pre_age[5,2]+df_post_age[5,2]))
1-(df_pre_hist[1,2]/(df_pre_hist[1,2] + df_post_hist[1,2] ))
1-(df_pre_hist[2,2]/(df_pre_hist[2,2] + df_post_hist[2,2] ))
1-(df_pre_hist[3,2]/(df_pre_hist[3,2] + df_post_hist[3,2] ))
1-(df_pre_hist[4,2]/(df_pre_hist[4,2] + df_post_hist[4,2] ))
   
```


